In [183]:
import numpy as np 
import pandas as pd
ca2015 = pd.read_csv('../../data/vax_df/ca_vax_df_2015.csv')
fl2015 = pd.read_csv('../../data/vax_df/fl_vax_df_2015.csv')
il2015 = pd.read_csv('../../data/vax_df/il_vax_df_2015.csv')
tx2015 = pd.read_csv('../../data/vax_df/tx_vax_df_2015.csv')
ca2018 = pd.read_csv('../../data/vax_df/ca_vax_df_2018.csv')
fl2019 = pd.read_csv('../../data/vax_df/fl_vax_df_2019.csv')
il2018 = pd.read_csv('../../data/vax_df/il_vax_df_2018.csv')
tx2018 = pd.read_csv('../../data/vax_df/tx_vax_df_2018.csv')
mi2018 = pd.read_csv('../../data/vax_df/mi_vax_df_2019.csv')




pres_df = pd.read_csv('../../data/pres.csv')
pres_df2016 = pres_df[pres_df.year == 2016]
pres_df2016['fips'] = pres_df2016['FIPS']
pres_df2016 = pres_df2016.drop(['FIPS', 'Unnamed: 0'], axis=1)

pres_df2020 = pd.read_csv('../../data/pres2020.csv')
pres_df2020['fips'] = pres_df2020['FIPS']
pres_df2020 = pres_df2020.drop(['FIPS', 'Unnamed: 0'], axis=1)

census2015 = pd.read_csv('../../data/df2015.csv')
census2019 = pd.read_csv('../../data/df2019.csv')
census2015 = census2015.drop(['Unnamed: 0','unnamed:_0'], axis=1)
census2015['county_fip'] = census2015.county_fip.astype(str).str.zfill(3)
census2015['state_fip'] = census2015.state_fip.astype(str).str.zfill(2)
census2015['fips'] = census2015['state_fip']+census2015['county_fip']
census2015 = census2015.drop(['state_fip','county_fip'], axis=1)
census2015['fips'] = census2015['fips'].astype(int)

df2015_16 = df2015_16[['fips', 'vax_percentage', 'total_agriculture', 'total_construction',
       'total_manufacturing', 'total_wholesale_trade', 'total_retail_trade',
       'transportation_warehousing_utilities', 'total_information',
       'total_finance_and_real_estate',
       'total_scientific_administrative_and_waste_management_services',
       'total_educational_healthcare_and_social_assistance',
       'total_arts_and_entertainment', 'total_other_services',
       'total_public_administration',
       'total_management_business_science_and_arts_occupations',
       'total_service_occupations', 'total_sales_and_office_occupations',
       'total_natural_resources_and_maintenance_occupations',
       'total_production,_transportation,_and_material_moving_occupations',
       'population_of_one_race_total', 'white', 'black_or_african_american',
       'american_indian_and_alaska_native', 'asian_alone',
       'native_hawaiian_and_other_pacific_islander',
       'population_of_one_race_some_other_race', 'median_age:_total',
       'ed_total', 'ed_no_schooling_completed', 'ed_nursery_school',
       'ed_kindergarten', 'ed_1st_grade', 'ed_2nd_grade', 'ed_3rd_grade',
       'ed_4th_grade', 'ed_5th_grade', 'ed_6th_grade', 'ed_7th_grade',
       'ed_8th_grade', 'ed_9th_grade', 'e_10th_grade', 'ed_11th_grade',
       'ed_12th_grade_no_diploma', 'median_income',
       'unemployed_pop_16_years_and_over', 'in_civilian_labor_force',
       'under_19_no_health_insurance_coverage',
       '19_to_34_years_no_health_insurance_coverage',
       '35_to_64_years_no_health_insurance_coverage', 
       '65_years_and_over_no_health_insurance_coverage','health_insurance_total',
       'total_population_estimate', 'year', 'office', 'state', 'dem_votes',
       'rep_votes', 'total_votes', 'target', 'State', 'County [2]',
       'Population(2010)', 'Land Areami²', 'Water Areami²', 'Total Areami²',
       'Latitude', 'Longitude']]

census2019 = census2019.drop(['Unnamed: 0','unnamed:_0'], axis=1)
census2019['county_fip'] = census2019.county_fip.astype(str).str.zfill(3)
census2019['state_fip'] = census2019.state_fip.astype(str).str.zfill(2)
census2019['fips'] = census2019['state_fip']+census2019['county_fip']
census2019 = census2019.drop(['state_fip','county_fip'], axis=1)
census2019['fips'] = census2019['fips'].astype(int)

<ipython-input-183-daeb3a885d6e>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pres_df2016['fips'] = pres_df2016['FIPS']

In [117]:
vax2015 = pd.concat([ca2015, fl2015, il2015, tx2015])
vax2019 = pd.concat([ca2018, fl2019, il2018, tx2018, mi2018])

In [118]:
pres_df2020.state.unique()

array(['CA', 'FL', 'IL', 'MI', 'TX'], dtype=object)

In [190]:
df2015_16.columns

Index(['fips', 'vax_percentage', 'total_agriculture', 'total_construction',
       'total_manufacturing', 'total_wholesale_trade', 'total_retail_trade',
       'transportation_warehousing_utilities', 'total_information',
       'total_finance_and_real_estate',
       'total_scientific_administrative_and_waste_management_services',
       'total_educational_healthcare_and_social_assistance',
       'total_arts_and_entertainment', 'total_other_services',
       'total_public_administration',
       'total_management_business_science_and_arts_occupations',
       'total_service_occupations', 'total_sales_and_office_occupations',
       'total_natural_resources_and_maintenance_occupations',
       'total_production,_transportation,_and_material_moving_occupations',
       'population_of_one_race_total', 'white', 'black_or_african_american',
       'american_indian_and_alaska_native', 'asian_alone',
       'native_hawaiian_and_other_pacific_islander',
       'population_of_one_race_some_other_race', 'median_age:_total',
       'ed_total', 'ed_no_schooling_completed', 'ed_nursery_school',
       'ed_kindergarten', 'ed_1st_grade', 'ed_2nd_grade', 'ed_3rd_grade',
       'ed_4th_grade', 'ed_5th_grade', 'ed_6th_grade', 'ed_7th_grade',
       'ed_8th_grade', 'ed_9th_grade', 'e_10th_grade', 'ed_11th_grade',
       'ed_12th_grade_no_diploma', 'median_income',
       'unemployed_pop_16_years_and_over', 'in_civilian_labor_force',
       'under_19_no_health_insurance_coverage',
       '19_to_34_years_no_health_insurance_coverage',
       '35_to_64_years_no_health_insurance_coverage',
       '65_years_and_over_no_health_insurance_coverage',
       'health_insurance_total', 'total_population_estimate', 'year', 'office',
       'state', 'dem_votes', 'rep_votes', 'total_votes', 'target', 'State',
       'County [2]', 'Population(2010)', 'Land Areami²', 'Water Areami²',
       'Total Areami²', 'Latitude', 'Longitude', 'insured_rate'],
      dtype='object')

In [119]:
df2015 = pd.merge(vax2015, census2015, on = 'fips')
df2015_16 = pd.merge(df2015, pres_df2016, on = 'fips')



#df2015.head()


df2015_16.to_csv('../../data/df2015_16.csv', index=False)

df2019 = pd.merge(vax2019, census2019, on = 'fips')
df2019_20 = pd.merge(df2019, pres_df2020, on = 'fips')
df2015_16.to_csv('../../data/df2019_20.csv', index=False)

In [169]:
row_sums = []
for row in df2015_16.index:
    row_sums.append(df2015_16.iloc[row, 29:44].sum())

In [187]:
insurance_sums = []
for row in df2015_16.index:
    insurance_sums.append(df2015_16.iloc[row, 47:51].sum())
df2015_16['insured_rate'] = insurance_sums/df2015_16.iloc[row, 52]

In [194]:
df2015_16.iloc[:, 21:30]

,white,black_or_african_american,american_indian_and_alaska_native,asian_alone,native_hawaiian_and_other_pacific_islander,population_of_one_race_some_other_race,median_age:_total,ed_total,ed_no_schooling_completed
0,708558,184883,9813,439055,13760,131339,37.1,1092189,25753
1,32006,855,829,538,38,1524,50.0,28676,304
2,185408,3189,2553,9591,405,7297,36.8,143094,2479
3,41210,261,396,402,151,532,50.7,33649,296
4,18188,151,231,419,39,1629,34.0,13296,336
...,...,...,...,...,...,...,...,...,...
474,683,15,7,17,0,199,46.1,739,17
475,1768,144,11,11,0,10,32.4,1166,10
476,2562,106,62,6,0,279,37.0,2052,74
477,1500,3,0,8,0,0,49.6,1137,16
478,13905,161,0,0,0,242,29.2,7958,133